"""add validation errors

Revision ID: 4e74f7304ccb
Revises: 7443a67d0396
Create Date: 2026-09-10 10:24:02.792080

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e74f7304ccb'
down_revision: Union[str, Sequence[str], None] = '7443a67d0396'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('validation_errors', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'validation_errors')
    # ### end Alembic commands ###
